print("      F")
print("     Fu")
print("    Fun")
print("   Funw")
print("  Funwi")
print(" Funwit")
print("Funwith")
print(" Funwit")
print("  Funwi")
print("   Funw")
print("    Fun")
print("     Fu")
print("      F")
