print("      F")
print("     F u")
print("    F u n")
print("   F u n w")
print("  F u n w i")
print(" F u n w i t")
print("F u n w i t h")
print(" F u n w i t")
print("  F u n w i")
print("   F u n w")
print("    F u n")
print("     F u")
print("      F")
